name: ecommerce-copy

services:
  db:
    image: mysql:8.0
    container_name: ecommerce-copy-db
    restart: always
    environment:
      MYSQL_DATABASE: 'sms'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3308:3306'
    volumes:
      - db_data_copy:/var/lib/mysql
    command: --innodb-buffer-pool-size=256M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-network-copy

  backend:
    build: ./demo
    container_name: ecommerce-copy-backend
    restart: always
    ports:
      - '8080:8080'
      - '8084:8080'
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sms
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
    volumes:
      - ./uploads:/app/uploads
    networks:
      - my-network-copy

  frontend:
    build: ./frontend
    container_name: ecommerce-copy-frontend
    restart: always
    ports:
      - '8085:80'
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    networks:
      - my-network-copy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ecommerce-copy-phpmyadmin
    restart: always
    ports:
      - "8086:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
      PMA_ROOT_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my-network-copy

volumes:
  db_data_copy:

networks:
  my-network-copy: